### ISSUE TITLE
System.out and System.err should probably not be redirected by default

### ISSUE THREAD

**Issue by MattiDragon** [LukasDetermann/shadow#2]
Shadow redirects `System.out` and `System.err` to annotation processor logging apis by default. This is not a good default, and can in some cases unexpectedly break things. For example, when running a shadow based annotation processor under gradle 8.9 or later, the build always fails. This is due to gradle now printing annotation processor output through `System.err` of the same jvm that's running the annotation processor. As shadow by defualt prints a note about the run time of the processor, this gets in an infinite loop where any ap logging is repeated until the javac error limit is reached.

This output redirection seems like a hack to work around badly written APs that don't use correct logging methods. I suggest it be disabled by default.

**Comment by LukasDetermann** [comment]
Thanks for the feedback. I will try to resolve it this week. If you have an example project that you can share, that would be great.

As a workaround, you can define your own with AP_Context#setSystemOutHandler and AP_Context#setSystemErrorHandler.

One of the goals of this project is to lower the barrier of entry for annotation processing. I think it's one of the main reasons why reflection, for example, is used so much more. Copying java.lang.System#out and java.lang.System#err to the javax.annotation.processing.Messager hopefully helps a little bit. It should enable System.out.println in annotation processors.

**Comment by MattiDragon** [comment]
Already applied the workaround to my AP. 

While I agree that redirecting stdout and stderr allows newcomers to avoid a pitfall, it also now leads to confusing errors with one of the most popular build tools.

A potential solution would be to disable the redirect while a message is being logged the correct way through shadow. That should mostly fix the bug without any issues.

I can prepare a repro later, but all you really need to do is use any shadow based AP in a gradle project using gradle 8.9 or later.

**Comment by LukasDetermann** [comment]
Yeah, it should work with Gradle. I'm not sure where the problem is. If a message is logged with the correct API, the proxy currently does nothing. Could you provide a sample project? The last time I used Gradle was for an Android 4.4 app :D

**Comment by LukasDetermann** [comment]
javac defaults to logging with System#err `com.sun.tools.javac.api.JavacTool#getTask`.
The System#err proxy delegated every write to `javax.annotation.processing.Messager#printMessage`, completing the loop.
The System#err proxy has been removed.

I'm not aware of any problems with the System#out proxy.
